baseURL = 'https://tifan.me/'
languageCode = 'en_US'
title = 'Tifan Dwi Avianto'
pluralizelisttitles = 'false'
enableRobotsTXT = 'true'
enableGitInfo = 'true'
enableEmoji = 'true'
[params]
    author = 'Tifan Dwi Avianto'
    description = "Tifan's blog containing tech and personal-related posts"
[taxonomies]
    techtag = 'techtags'
    personaltag = 'personaltags'
[permalinks]
    techtags = '/tech/tags/:title'
    personaltags = '/personal/tags/:title'
[markup]
    [highlight]
        noClasses = 'false'
        lineNumbersInTable = 'false'
        guessSyntax = 'true'
        lineNos = 'true'
    [goldmark]
        [renderer]
            unsafe = 'true'
            hardWraps = 'true'