baseURL = 'https://tifan.me/'
languageCode = 'en'
title = 'Tifan Dwi Avianto'
pluralizelisttitles = 'false'
enableRobotsTXT = 'true'
enableGitInfo = 'true'
enableEmoji = 'true'
markup.highlight.noClasses = 'false'
markup.highlight.lineNos = 'true'
markup.highlight.lineNumbersInTable = 'false'
markup.highlight.guessSyntax = 'true'
markup.goldmark.renderer.unsafe = 'true'
markup.goldmark.renderer.hardWraps = 'true'
[params]
    author = 'Tifan Dwi Avianto'
    description = "Tifan's blog containing tech and personal-related posts"
[taxonomies]
    techtag = 'techtags'
    personaltag = 'personaltags'
[permalinks]
    techtags = '/tech/tags/:title'
    personaltags = '/personal/tags/:title'