baseURL = 'https://tifan.me/'
languageCode = 'en-us'
title = 'Tifan Dwi Avianto'
pluralizelisttitles = 'false'
enableRobotsTXT = 'true'
enableGitInfo = 'true'
googleAnalytics = '339702002'
[params]
    author = 'Tifan Dwi Avianto'
    description = "Tifan's blog containing tech and personal-related posts"